const categoryUrl = [{
    "id": 19,
    "url": 'committee_iso_work',
    "name": "ISO/TC21/SC6工作动态"
  }, {
    "id": 15,
    "url": 'committee_one_work',
    "name": "一分委工作动态"
  }, {
    "id" :17,
    "url": 'committee_three_work',
    "name": "三分委工作动态"
  }, {
    "id": 1,
    "url": 'center_intro',
    "name": "中心概况"
  }, {
    "id": 16,
    "url": 'committee_two_work',
    "name": "二分委工作动态"
  }, {
    "id": 18,
    "url": 'committee_eight_work',
    "name": "八分委工作动态"
  }, {
    "id": 12,
    "url": 'imgNews',
    "name": "图片新闻"
  }, {
    "id": 5,
    "url": 'center_address',
    "name": "地理位置"
  }, {
    "id": 3,
    "url": 'center_certificate',
    "name": "授权证书"
  }, {
    "id": 20,
    "url": '',
    "name": "文件下载"
  }, {
    "id": 2,
    "url": 'center_law',
    "name": "法律地位"
  }, {
    "id": 14,
    "url": 'law',
    "name": "法律法规"
  }, {
    "id": 9,
    "url": 'inspect_equipment',
    "name": "消防装备产品"
  }, {
    "id": 6,
    "url": 'inspect_119',
    "name": "火灾报警产品"
  }, {
    "id": 7,
    "url": 'inspect_protect',
    "name": "火灾防护产品"
  }, {
    "id": 8,
    "url": 'inspect_outfire',
    "name": "灭火设备产品"
  }, {
    "id": 13,
    "url": 'trends',
    "name": "行业动态"
  }, {
    "id": 11,
    "url": 'notification',
    "name": "通知公告"
  }, {
    "id": 4,
    "url": 'center_facility',
    "name": "重点设备"
  }, {
    "id": 10,
    "url": 'inspect_3c',
    "name": "非3C认证产品"
}]

export default categoryUrl
